# backend/app/schemas/payload.py

from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


class OperationalDomain(str, Enum):
    """
    Enumeration of standardized academic domains for task classification.
    """

    PEDAGOGY = "PEDAGOGY"
    ADMINISTRATION = "ADMINISTRATION"
    RESEARCH = "RESEARCH"
    EVALUATION = "EVALUATION"
    OTHER = "OTHER"


class CategorizedTask(BaseModel):
    """
    Schema representing a single standardized task parsed from raw input.
    """

    domain: OperationalDomain = Field(
        ..., description="The classified operational domain."
    )
    action: str = Field(
        ..., description="A concise description of the completed action."
    )
    metric: Optional[str] = Field(
        None, description="Quantifiable metric, such as duration or count."
    )


class DailySummaryReport(BaseModel):
    """
    Schema representing the final drafted report generated by the Summarization Agent.
    """

    executive_summary: str = Field(
        ..., description="A brief paragraph summarizing the day's primary focus."
    )
    completed_activities: List[CategorizedTask] = Field(
        ..., description="List of all categorized tasks."
    )
